apiVersion: v1
kind: Service
metadata:
  name: alm
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: alm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alm 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alm
  template:
    metadata:
      labels:
        app: alm
    spec:
      containers:
      - name: mssql
        image: nikolaypeshev/alm_mssql:1.0
        ports:
        - containerPort: 1433
      containers:
      - name: alm
        image: nikolaypeshev/alm:16
        ports:
        - containerPort: 8080