apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 1433
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: nikolaypeshev/alm_mssql:1.0
        ports:
        - containerPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: alm
spec:
  ports:
  - port: 8080
  selector:
    app: alm
---
apiVersion: v1
kind: Service
metadata:
  name: alm
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: alm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alm 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alm
  template:
    metadata:
      labels:
        app: alm
    spec:
      containers:
      - name: alm
        image: nikolaypeshev/alm:16
        ports:
        - containerPort: 8080