apiVersion: apps/v1
kind: Deployment
metadata:
  name: autopass
spec:
  selector:
    matchLabels:
      app: autopass
  replicas: 1
  template:
    metadata:
      labels:
        app: autopass
    spec:
      containers:
      - name: autopass
        image: nikolaypeshev/autopass:12.3
        ports:
        - containerPort: 5814
---
apiVersion: v1
kind: Service
metadata:
  name: autopass-np
spec:
  type: NodePort 
  ports:
  - port: 5814
    targetPort: 5814
    protocol: TCP
    name: https
  selector:
    app: autopass